/** Region stored on every topic; the forum currently covers only the Federal District. */
export const FORUM_REGION = 'DF';

/** Administrative regions (RAs) of the Federal District, used as the topic "city". */
export const FORUM_CITIES = [
  'Plano Piloto',
  'Gama',
  'Taguatinga',
  'Brazlândia',
  'Sobradinho',
  'Planaltina',
  'Paranoá',
  'Núcleo Bandeirante',
  'Ceilândia',
  'Guará',
  'Cruzeiro',
  'Samambaia',
  'Santa Maria',
  'São Sebastião',
  'Recanto das Emas',
  'Lago Sul',
  'Riacho Fundo',
  'Lago Norte',
  'Candangolândia',
  'Águas Claras',
  'Riacho Fundo II',
  'Sudoeste/Octogonal',
  'Varjão',
  'Park Way',
  'SCIA/Estrutural',
  'Sobradinho II',
  'Jardim Botânico',
  'Itapoã',
  'SIA',
  'Vicente Pires',
  'Fercal',
  'Sol Nascente/Pôr do Sol',
  'Arniqueira',
  'Arapoanga',
  'Água Quente',
] as const;
